import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('textbox', { name: 'Five-digit zip code' }).click();
  await page.getByRole('textbox', { name: 'Five-digit zip code' }).fill('01003');
  await page.locator('div').filter({ hasText: /^Oil change$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Battery replacement$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Brake service$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Tire change\/rotation$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Engine repair$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Diagnostics$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^AC recharge$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Coolant & fluids$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Belts & hoses$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Starter\/alternator$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Spark plugs$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Scheduled maintenance$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^State inspection$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Suspension$/ }).nth(1).click();
  await page.getByText('-456-7890').click();
  await page.getByText('Contact Us').click();
  await page.getByText('help@mobilemechanic.com').click();
  await page.getByRole('button', { name: 'Go' }).click();
  await page.getByRole('button', { name: 'View/upload images' }).click();
  await page.getByRole('button', { name: 'Modify booking' }).click();
  await page.getByRole('button', { name: 'Messages' }).click();
  await page.getByRole('button', { name: 'Open Chat' }).first().click();
  await page.getByRole('button', { name: 'Open Chat' }).first().click();
  await page.getByRole('button', { name: 'Open Chat' }).nth(1).click();
  await page.getByText('You: My neighbors love to').click();
  await page.locator('div').nth(3).click();
  await page.getByRole('button', { name: 'Create Appointment' }).click();
  await page.getByRole('button', { name: '09:45' }).click();
  await page.getByRole('button', { name: '14:30' }).click();
  await page.getByRole('button', { name: 'Saturday, June 28th,' }).click();
  await page.getByRole('button', { name: 'Go to the Next Month' }).dblclick();
  await page.getByRole('button', { name: 'Friday, August 15th,' }).click();
  await page.getByRole('button', { name: '16:30' }).click();
  await page.getByRole('textbox', { name: 'Make' }).click();
  await page.getByRole('textbox', { name: 'Model' }).click();
  await page.getByRole('spinbutton', { name: 'Year' }).click();
  await page.getByRole('textbox', { name: 'Issue Description' }).click();
  await page.getByRole('button', { name: 'Upload Image' }).click();
  await page.getByRole('button', { name: 'Billing' }).click();
  await page.getByRole('button', { name: 'John Doe' }).click();
  await page.getByRole('paragraph').filter({ hasText: /^John Doe$/ }).click();
  await page.getByRole('button', { name: 'Mobile Mechanic' }).click();
});