# .github/workflows/lint-backend.yml
name: Lint Backend

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/lint-backend.yml'
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Ruff
        run: pip install ruff
      
      - name: Run Ruff linter
        run: ruff check backend/
      
      - name: Run Ruff formatter check
        run: ruff format --check backend/
